"n_channels" : '[5, 8, 12, 16]'
"input_dim": 5
"sequence_length": 20
"out_dim" : 3
"kernel": '[4, 4, 3]'
"stride": '[2, 2, 1]'
"dilation": '[1, 1, 1]'
"non_linearity" : "nn.ReLU6" #  nn.ReLU, nn.ReLU6, nn.LeakyReLU, nn.ELU, nn.Tanh
"datadir": ""
"learning_rate" : 0.0003
"optimizer" : adam
"weight_decay" : 0.0003
"test_size" : 0.2
"batchsize" : 128
"num_epochs": 80
"balance": True
"filter": "pastmean" # pastmean, smooth
"pastmean_k": 5
"smoothness": 0.2 # lower is smoother
"normalizelbl": True
"normcnst": []
"cliplabel": 1
