"n_channels" : '[5, 16, 32, 64]'
"input_dim": 5
"sequence_length": 100
"out_dim" : 3
"kernel": '[16, 8, 8]'
"stride": '[4, 2, 1]'
"dilation": '[1, 1, 1]'
"non_linearity" : "nn.ReLU6" #  nn.ReLU, nn.ReLU6, nn.LeakyReLU, nn.ELU, nn.Tanh
"datadir": ""
"learning_rate" : 0.0001
"optimizer" : adam
"weight_decay" : 0.0003
"test_size" : 0.2
"batchsize" : 256
"num_epochs": 30
"balance": False
"dimbalance": 2
"filter": "" # pastmean, smooth
"pastmean_k": 10
"smoothness": 0.2 # lower is smoother
"normalizelbl": True
"normcnst": []
"cliplabel": 1
