"input_dim" : 5
"output_dim" : 3
"hidden_dim" : 64
"n_hidden": 2
"sequence_length": 1
"everyn": 1
"non_linearity" : "nn.ReLU6" #  nn.ReLU, nn.ReLU6, nn.LeakyReLU, nn.ELU, nn.Tanh
"dropout": 0.
"datadir": ""
"learning_rate" : 0.0003
"weight_decay" : 0.00
"test_size" : 0.2
"batchsize" : 128
"num_epochs": 80
"balance": True
"filter": "" # pastmean, smooth
"pastmean_k": 10
"smoothness": 0.2 # lower is smoother
"normalizelbl": True
"normcnst": []
"cliplabel": 1
